package ch.heigvd.iict.sym.sym_labo4;

import android.app.Notification;
import android.app.PendingIntent;
import android.content.Intent;
import android.os.Bundle;
import android.support.v4.app.NotificationCompat;
import android.support.v4.app.NotificationManagerCompat;
import android.support.v4.app.TaskStackBuilder;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.Button;
import android.widget.Toast;

import ch.heigvd.iict.sym.wearcommon.Constants;

public class NotificationActivity extends AppCompatActivity {
    private Button pendingIntentButton;
    private Button actionButtonButton;
    private Button wearableOnlyButton;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_notification);

        if (getIntent() != null)
            onNewIntent(getIntent());

        pendingIntentButton = findViewById(R.id.button_notif_builder);
        actionButtonButton = findViewById(R.id.action_notif_button);
        wearableOnlyButton = findViewById(R.id.wear_action_notif);

        pendingIntentButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                pendingIntentNotification();
            }
        });

        actionButtonButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                actionButtonNotification();
            }
        });

        wearableOnlyButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                wearableOnlyNotification();
            }
        });
    }

    private void pendingIntentNotification() {
        String id = "my_channel_01";

        String title = "Title";
        String text = "Notification Text";

        PendingIntent viewPendingIntent = createPendingIntent(0, text);

        NotificationCompat.Builder builder = new NotificationCompat.Builder(this, id)
                .setSmallIcon(R.drawable.ic_lightbulb_on_black_18dp)
                .setContentTitle(title)
                .setContentText(text)
                .setContentIntent(viewPendingIntent);

        notify(builder.build());
    }

    private void actionButtonNotification() {
        String id = "my_channel_02";

        String title = "Title";
        String text = "Notification Text";

        PendingIntent viewPendingIntent = createPendingIntent(0, text);

        NotificationCompat.Builder builder = new NotificationCompat.Builder(this, id)
                .setSmallIcon(R.drawable.ic_lightbulb_on_black_18dp)
                .setContentTitle(title)
                .setContentText(text)
                .addAction(R.drawable.ic_alert_black_18dp, "Click to display a toast on the phone.",
                        viewPendingIntent);

        notify(builder.build());
    }

    private void wearableOnlyNotification() {
        String id = "my_channel_02";

        String title = "Title";
        String text = "Notification Text";

        PendingIntent viewPendingIntent = createPendingIntent(0, text);

        NotificationCompat.WearableExtender wearableExtender =
                new NotificationCompat.WearableExtender().setHintHideIcon(true);

        NotificationCompat.Builder builder = new NotificationCompat.Builder(this, id)
                .setSmallIcon(R.drawable.ic_lightbulb_on_black_18dp)
                .setContentTitle(title)
                .setContentText(text)
                .extend(wearableExtender)
                .addAction(R.drawable.ic_alert_black_18dp, "Display the toast on the phone!",
                        viewPendingIntent);

        notify(builder.build());
    }

    private void notify(Notification notification) {
        NotificationManagerCompat notificationManager = NotificationManagerCompat.from(this);
        notificationManager.notify(1, notification);
    }

    /*
     *  Code fourni pour les PendingIntent
     */

    /*
     *  Method called by system when a new Intent is received
     *  Display a toast with a message if the Intent is generated by
     *  createPendingIntent method.
     */
    @Override
    protected void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        if (intent == null) return;
        if (Constants.MY_PENDING_INTENT_ACTION.equals(intent.getAction()))
            Toast.makeText(this, "" + intent.getStringExtra("msg"), Toast.LENGTH_SHORT).show();
    }

    /**
     * Method used to create a PendingIntent with the specified message
     * The intent will start a new activity Instance or bring to front an existing one.
     * See parentActivityName and launchMode options in Manifest
     * See https://developer.android.com/training/notify-user/navigation.html for TaskStackBuilder
     *
     * @param requestCode The request code
     * @param message     The message
     * @return The pending Intent
     */
    private PendingIntent createPendingIntent(int requestCode, String message) {
        Intent myIntent = new Intent(NotificationActivity.this, NotificationActivity.class);
        myIntent.setAction(Constants.MY_PENDING_INTENT_ACTION);
        myIntent.putExtra("msg", message);

        TaskStackBuilder stackBuilder = TaskStackBuilder.create(this);
        stackBuilder.addParentStack(NotificationActivity.class);
        stackBuilder.addNextIntent(myIntent);

        return stackBuilder.getPendingIntent(requestCode, PendingIntent.FLAG_UPDATE_CURRENT);
    }

}
